//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebColumns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WebColumns()
        {
            this.Articles = new HashSet<Articles>();
            this.Summaries = new HashSet<Summaries>();
            this.WebColumns1 = new HashSet<WebColumns>();
        }
    
        public int Id { get; set; }
        public int Sort { get; set; }
        public string Name { get; set; }
        public Nullable<int> Position { get; set; }
        public int ModuleType { get; set; }
        public bool IsOpenNew { get; set; }
        public bool CanAddContent { get; set; }
        public string Title { get; set; }
        public string Keyword { get; set; }
        public string Description { get; set; }
        public int Level { get; set; }
        public bool IsShow { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public Nullable<int> WebSite_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articles> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Summaries> Summaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WebColumns> WebColumns1 { get; set; }
        public virtual WebColumns WebColumns2 { get; set; }
        public virtual WebSites WebSites { get; set; }
    }
}
